In [1]:
import pandas as pd
import numpy as np
from statsmodels.api import Logit
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv("실기 Python 실습파일 (2)/iris.csv")
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [3]:
df["Species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df["is_setosa"] = (df["Species"] == "setosa") +0
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  is_setosa
0           5.1          3.5           1.4          0.2  setosa          1
1           4.9          3.0           1.4          0.2  setosa          1

In [8]:
df.iloc[:2,:2]

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0

In [6]:
model = Logit(endog = df["is_setosa"],
              exog = df.iloc[:,:2]).fit()
model

Optimization terminated successfully.
         Current function value: 0.036374
         Iterations 11


In [9]:
model.params

Sepal.Length    -7.529945
Sepal.Width     13.130734
dtype: float64

In [10]:
model.pvalues

Sepal.Length    0.000828
Sepal.Width     0.000989
dtype: float64

In [11]:
model.tvalues

Sepal.Length   -3.343109
Sepal.Width     3.293594
dtype: float64

In [12]:
pred = model.predict(df.iloc[:3,:2])
pred

0    0.999477
1    0.923824
2    0.998678
dtype: float64

In [13]:
(pred > 0.5) + 0

0    1
1    1
2    1
dtype: int32

In [17]:
model = LogisticRegression(random_state= 123)
model.fit(X = df.iloc[:,:2],
          y = df["is_setosa"])
model

LogisticRegression(random_state=123)

In [18]:
model.coef_

array([[-3.38829757,  3.1645277 ]])

In [19]:
model.intercept_ #절편

array([8.32330389])

In [22]:
pred = model. predict_proba(df.iloc[:3, :2])
pred = pred[:,1]
pred

array([0.89272024, 0.77104635, 0.92586179])

In [23]:
(pred > 0.5) + 0

array([1, 1, 1])

In [24]:
pred = model. predict_proba(df.iloc[:, :2])
pred = pred[:,1]
pred[:10]

array([0.89272024, 0.77104635, 0.92586179, 0.92738323, 0.94126096,
       0.91436651, 0.97058885, 0.89484454, 0.93034007, 0.82210603])

In [25]:
from sklearn.metrics import roc_auc_score

In [27]:
roc_auc_score(y_true = df["is_setosa"],
              y_score = pred)

0.9999999999999999

In [29]:
accuracy_score(y_true = df["is_setosa"],
               y_pred = (pred >0.8)+0)

0.9466666666666667

# 문제

Q1.

In [30]:
df = pd.read_csv("실기 Python 실습파일 (2)/diabetes.csv")
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
df_train, df_test = train_test_split(df, train_size=0.8, random_state= 123)
df_train.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
318            3      115             66             39      140  38.1   
313            3      113             50             10       85  29.5   

     DiabetesPedigreeFunction  Age  Outcome  
318                     0.150   28        0  
313                     0.626   25        0

In [33]:
model = Logit(endog = df_train["Outcome"],
              exog = df_train.loc[:,["BloodPressure", "Glucose", "BMI", "Insulin"]]).fit()
model

Optimization terminated successfully.
         Current function value: 0.626579
         Iterations 5


In [34]:
pred = model.predict(exog = df_test.loc[:,["BloodPressure", "Glucose", "BMI", "Insulin"]])
pred[:4]

236    0.462956
395    0.507051
36     0.359735
210    0.314389
dtype: float64

In [36]:
pred_class = (pred > 0.5)+0
pred_class[:4]

236    0
395    1
36     0
210    0
dtype: int32

In [37]:
accuracy_score(y_pred=pred_class, y_true= df_test["Outcome"])

0.7012987012987013

Q2.

In [38]:
df = pd.read_csv("실기 Python 실습파일 (2)/diabetes.csv")
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [39]:
model = Logit(endog = df_train["Outcome"],
              exog = df_train.loc[:,["Glucose", "BMI", "Age"]]).fit()
model.params

Optimization terminated successfully.
         Current function value: 0.654503
         Iterations 4


Glucose    0.008705
BMI       -0.033139
Age       -0.013766
dtype: float64

In [40]:
np.exp(model.params)

Glucose    1.008743
BMI        0.967404
Age        0.986328
dtype: float64

Q3.

In [41]:
df = pd.read_csv("실기 Python 실습파일 (2)/diabetes.csv")
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [42]:
model = Logit(endog = df_train["Outcome"],
              exog = df_train.loc[:,["Glucose", "BMI", "Age"]]).fit()

Optimization terminated successfully.
         Current function value: 0.654503
         Iterations 4


In [43]:
model.predict(df.loc[:,["Glucose", "BMI", "Age"]])[:5]

0    0.374395
1    0.361629
2    0.593969
3    0.390425
4    0.334043
dtype: float64

In [44]:
roc_auc_score(y_true=df["Outcome"],
              y_score= model.predict(df.loc[:,["Glucose", "BMI", "Age"]]))

0.5311119402985074